export enum apiRoutes {
  LOGIN = '/auth/login',
  SIGNUP = '/auth/signup',
  SIGNOUT = '/auth/signout',
  ME = '/auth/me',
  REFRESH_TOKENS = '/auth/refresh',
  FETCH_USERS = '/users',
  USERS_PREFIX = '/users',
  UPLOAD_AVATAR_IMAGE = '/users/upload',
  GET_AVATAR_IMAGE = '/users/get/image',
  QUOTES_PREFIX = '/quotes',
  FETCH_QUOTES = '/quotes',
  ME_QUOTES = '/quotes/me',
  VOTES_PREFIX = '/votes',
  FETCH_VOTES = '/votes',
  ME_VOTES = '/votes/me',
  FETCH_RECENT_QUOTES = '/quotes/recent',
  FETCH_RANDOM_QUOTE = '/quotes/random',
} 