export enum routes {
  LOGIN = '/login',
  SIGNUP = '/signup',
  HOME = '/',
  USERINFO = '/me',
  USEREDIT = '../me/edit',
  USERPASSWORDEDIT = '../me/update-password',
  USERAVATAREDIT = '../me/update-avatar',
  ADDNEWQUOTE='../me/myquote',
  USERQUOTESINFO='../me/quotes',
  EDITQUOTE='me/myquote/edit',
  DELETEQUOTE='me/myquote/delete',
  MOSTLIKEDQUOTES='quotes/most-liked',
  MOSTRECENTQUOTES='quotes/most-recent',
}